//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Apikey) DeepCopyInto(out *Apikey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Apikey.
func (in *Apikey) DeepCopy() *Apikey {
	if in == nil {
		return nil
	}
	out := new(Apikey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Apikey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApikeyInitParameters) DeepCopyInto(out *ApikeyInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(string)
		**out = **in
	}
	if in.ProjectRefRef != nil {
		in, out := &in.ProjectRefRef, &out.ProjectRefRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectRefSelector != nil {
		in, out := &in.ProjectRefSelector, &out.ProjectRefSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApikeyInitParameters.
func (in *ApikeyInitParameters) DeepCopy() *ApikeyInitParameters {
	if in == nil {
		return nil
	}
	out := new(ApikeyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApikeyList) DeepCopyInto(out *ApikeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Apikey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApikeyList.
func (in *ApikeyList) DeepCopy() *ApikeyList {
	if in == nil {
		return nil
	}
	out := new(ApikeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApikeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApikeyObservation) DeepCopyInto(out *ApikeyObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(string)
		**out = **in
	}
	if in.SecretJwtTemplate != nil {
		in, out := &in.SecretJwtTemplate, &out.SecretJwtTemplate
		*out = new(SecretJwtTemplateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApikeyObservation.
func (in *ApikeyObservation) DeepCopy() *ApikeyObservation {
	if in == nil {
		return nil
	}
	out := new(ApikeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApikeyParameters) DeepCopyInto(out *ApikeyParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(string)
		**out = **in
	}
	if in.ProjectRefRef != nil {
		in, out := &in.ProjectRefRef, &out.ProjectRefRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectRefSelector != nil {
		in, out := &in.ProjectRefSelector, &out.ProjectRefSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApikeyParameters.
func (in *ApikeyParameters) DeepCopy() *ApikeyParameters {
	if in == nil {
		return nil
	}
	out := new(ApikeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApikeySpec) DeepCopyInto(out *ApikeySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApikeySpec.
func (in *ApikeySpec) DeepCopy() *ApikeySpec {
	if in == nil {
		return nil
	}
	out := new(ApikeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApikeyStatus) DeepCopyInto(out *ApikeyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApikeyStatus.
func (in *ApikeyStatus) DeepCopy() *ApikeyStatus {
	if in == nil {
		return nil
	}
	out := new(ApikeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretJwtTemplateInitParameters) DeepCopyInto(out *SecretJwtTemplateInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretJwtTemplateInitParameters.
func (in *SecretJwtTemplateInitParameters) DeepCopy() *SecretJwtTemplateInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecretJwtTemplateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretJwtTemplateObservation) DeepCopyInto(out *SecretJwtTemplateObservation) {
	*out = *in
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretJwtTemplateObservation.
func (in *SecretJwtTemplateObservation) DeepCopy() *SecretJwtTemplateObservation {
	if in == nil {
		return nil
	}
	out := new(SecretJwtTemplateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretJwtTemplateParameters) DeepCopyInto(out *SecretJwtTemplateParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretJwtTemplateParameters.
func (in *SecretJwtTemplateParameters) DeepCopy() *SecretJwtTemplateParameters {
	if in == nil {
		return nil
	}
	out := new(SecretJwtTemplateParameters)
	in.DeepCopyInto(out)
	return out
}
