// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FunctionInitParameters struct {

	// Path to the function entrypoint file
	Entrypoint *string `json:"entrypoint,omitempty" tf:"entrypoint,omitempty"`

	// Path to the import map file
	ImportMap *string `json:"importMap,omitempty" tf:"import_map,omitempty"`

	// Name of the function (defaults to slug if not specified)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ref
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/cluster/project/v1alpha1.Project
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.Reference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.Selector `json:"projectRefSelector,omitempty" tf:"-"`

	// URL-friendly identifier for the function
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// List of glob patterns for static files to include
	StaticFiles []*string `json:"staticFiles,omitempty" tf:"static_files,omitempty"`
}

type FunctionObservation struct {

	// SHA256 checksum of the deployed function bundle (remote)
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// Timestamp when the function was created
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Path to the function entrypoint file
	Entrypoint *string `json:"entrypoint,omitempty" tf:"entrypoint,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Path to the import map file
	ImportMap *string `json:"importMap,omitempty" tf:"import_map,omitempty"`

	// SHA256 checksum of local source files before upload
	LocalChecksum *string `json:"localChecksum,omitempty" tf:"local_checksum,omitempty"`

	// Name of the function (defaults to slug if not specified)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ref
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// URL-friendly identifier for the function
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// List of glob patterns for static files to include
	StaticFiles []*string `json:"staticFiles,omitempty" tf:"static_files,omitempty"`

	// Function deployment status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Timestamp when the function was last updated
	UpdatedAt *float64 `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Currently deployed function version
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type FunctionParameters struct {

	// Path to the function entrypoint file
	// +kubebuilder:validation:Optional
	Entrypoint *string `json:"entrypoint,omitempty" tf:"entrypoint,omitempty"`

	// Path to the import map file
	// +kubebuilder:validation:Optional
	ImportMap *string `json:"importMap,omitempty" tf:"import_map,omitempty"`

	// Name of the function (defaults to slug if not specified)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ref
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.Reference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.Selector `json:"projectRefSelector,omitempty" tf:"-"`

	// URL-friendly identifier for the function
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// List of glob patterns for static files to include
	// +kubebuilder:validation:Optional
	StaticFiles []*string `json:"staticFiles,omitempty" tf:"static_files,omitempty"`
}

// FunctionSpec defines the desired state of Function
type FunctionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FunctionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FunctionInitParameters `json:"initProvider,omitempty"`
}

// FunctionStatus defines the observed state of Function.
type FunctionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FunctionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Function is the Schema for the Functions API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-supabase}
type Function struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entrypoint) || (has(self.initProvider) && has(self.initProvider.entrypoint))",message="spec.forProvider.entrypoint is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.slug) || (has(self.initProvider) && has(self.initProvider.slug))",message="spec.forProvider.slug is a required parameter"
	Spec   FunctionSpec   `json:"spec"`
	Status FunctionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FunctionList contains a list of Functions
type FunctionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Function `json:"items"`
}

// Repository type metadata.
var (
	Function_Kind             = "Function"
	Function_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Function_Kind}.String()
	Function_KindAPIVersion   = Function_Kind + "." + CRDGroupVersion.String()
	Function_GroupVersionKind = CRDGroupVersion.WithKind(Function_Kind)
)

func init() {
	SchemeBuilder.Register(&Function{}, &FunctionList{})
}
