// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FunctionSecretsInitParameters struct {

	// Project reference ID
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/cluster/project/v1alpha1.Project
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.Reference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.Selector `json:"projectRefSelector,omitempty" tf:"-"`

	Secrets []SecretsInitParameters `json:"secrets,omitempty" tf:"secrets,omitempty"`
}

type FunctionSecretsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Project reference ID
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Map of secret name to the SHA-256 hex digest of the secret value. Computed by the provider at plan time (when plaintext values are known) and updated after each apply.
	// +mapType=granular
	SecretDigests map[string]*string `json:"secretDigests,omitempty" tf:"secret_digests,omitempty"`

	Secrets []SecretsObservation `json:"secrets,omitempty" tf:"secrets,omitempty"`
}

type FunctionSecretsParameters struct {

	// Project reference ID
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.Reference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.Selector `json:"projectRefSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Secrets []SecretsParameters `json:"secrets,omitempty" tf:"secrets,omitempty"`
}

type SecretsInitParameters struct {

	// Name of the secret. Must not start with the `SUPABASE_` prefix — such names are reserved internally by Supabase, cannot be created, updated, or deleted via the API, and are automatically filtered out from reads and imports.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The plaintext secret value. After an import this field will be `null` because the Supabase API only returns SHA-256 digests — see the Import section below.
	ValueSecretRef v1.SecretKeySelector `json:"valueSecretRef" tf:"-"`
}

type SecretsObservation struct {

	// Name of the secret. Must not start with the `SUPABASE_` prefix — such names are reserved internally by Supabase, cannot be created, updated, or deleted via the API, and are automatically filtered out from reads and imports.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SecretsParameters struct {

	// Name of the secret. Must not start with the `SUPABASE_` prefix — such names are reserved internally by Supabase, cannot be created, updated, or deleted via the API, and are automatically filtered out from reads and imports.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The plaintext secret value. After an import this field will be `null` because the Supabase API only returns SHA-256 digests — see the Import section below.
	// +kubebuilder:validation:Optional
	ValueSecretRef v1.SecretKeySelector `json:"valueSecretRef" tf:"-"`
}

// FunctionSecretsSpec defines the desired state of FunctionSecrets
type FunctionSecretsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FunctionSecretsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FunctionSecretsInitParameters `json:"initProvider,omitempty"`
}

// FunctionSecretsStatus defines the observed state of FunctionSecrets.
type FunctionSecretsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FunctionSecretsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FunctionSecrets is the Schema for the FunctionSecretss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-supabase}
type FunctionSecrets struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secrets) || (has(self.initProvider) && has(self.initProvider.secrets))",message="spec.forProvider.secrets is a required parameter"
	Spec   FunctionSecretsSpec   `json:"spec"`
	Status FunctionSecretsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FunctionSecretsList contains a list of FunctionSecretss
type FunctionSecretsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FunctionSecrets `json:"items"`
}

// Repository type metadata.
var (
	FunctionSecrets_Kind             = "FunctionSecrets"
	FunctionSecrets_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FunctionSecrets_Kind}.String()
	FunctionSecrets_KindAPIVersion   = FunctionSecrets_Kind + "." + CRDGroupVersion.String()
	FunctionSecrets_GroupVersionKind = CRDGroupVersion.WithKind(FunctionSecrets_Kind)
)

func init() {
	SchemeBuilder.Register(&FunctionSecrets{}, &FunctionSecretsList{})
}
