// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ApikeyInitParameters struct {

	// Description of the API key
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the API key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project reference ID
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/namespaced/project/v1alpha1.Project
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.NamespacedReference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.NamespacedSelector `json:"projectRefSelector,omitempty" tf:"-"`
}

type ApikeyObservation struct {

	// Description of the API key
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the API key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project reference ID
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	SecretJwtTemplate *SecretJwtTemplateObservation `json:"secretJwtTemplate,omitempty" tf:"secret_jwt_template,omitempty"`

	// Type of the API key
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ApikeyParameters struct {

	// Description of the API key
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the API key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project reference ID
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.NamespacedReference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.NamespacedSelector `json:"projectRefSelector,omitempty" tf:"-"`
}

type SecretJwtTemplateInitParameters struct {
}

type SecretJwtTemplateObservation struct {

	// Role of the secret JWT template
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type SecretJwtTemplateParameters struct {
}

// ApikeySpec defines the desired state of Apikey
type ApikeySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ApikeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApikeyInitParameters `json:"initProvider,omitempty"`
}

// ApikeyStatus defines the observed state of Apikey.
type ApikeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ApikeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Apikey is the Schema for the Apikeys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-supabase}
type Apikey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ApikeySpec   `json:"spec"`
	Status ApikeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApikeyList contains a list of Apikeys
type ApikeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Apikey `json:"items"`
}

// Repository type metadata.
var (
	Apikey_Kind             = "Apikey"
	Apikey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Apikey_Kind}.String()
	Apikey_KindAPIVersion   = Apikey_Kind + "." + CRDGroupVersion.String()
	Apikey_GroupVersionKind = CRDGroupVersion.WithKind(Apikey_Kind)
)

func init() {
	SchemeBuilder.Register(&Apikey{}, &ApikeyList{})
}
