// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BranchInitParameters struct {

	// Git branch
	GitBranch *string `json:"gitBranch,omitempty" tf:"git_branch,omitempty"`

	// Parent project ref
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/namespaced/project/v1alpha1.Project
	ParentProjectRef *string `json:"parentProjectRef,omitempty" tf:"parent_project_ref,omitempty"`

	// Reference to a Project in project to populate parentProjectRef.
	// +kubebuilder:validation:Optional
	ParentProjectRefRef *v1.NamespacedReference `json:"parentProjectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate parentProjectRef.
	// +kubebuilder:validation:Optional
	ParentProjectRefSelector *v1.NamespacedSelector `json:"parentProjectRefSelector,omitempty" tf:"-"`

	// Database region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type BranchObservation struct {
	Database *DatabaseObservation `json:"database,omitempty" tf:"database,omitempty"`

	// Git branch
	GitBranch *string `json:"gitBranch,omitempty" tf:"git_branch,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Parent project ref
	ParentProjectRef *string `json:"parentProjectRef,omitempty" tf:"parent_project_ref,omitempty"`

	// Database region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type BranchParameters struct {

	// Git branch
	// +kubebuilder:validation:Optional
	GitBranch *string `json:"gitBranch,omitempty" tf:"git_branch,omitempty"`

	// Parent project ref
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ParentProjectRef *string `json:"parentProjectRef,omitempty" tf:"parent_project_ref,omitempty"`

	// Reference to a Project in project to populate parentProjectRef.
	// +kubebuilder:validation:Optional
	ParentProjectRefRef *v1.NamespacedReference `json:"parentProjectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate parentProjectRef.
	// +kubebuilder:validation:Optional
	ParentProjectRefSelector *v1.NamespacedSelector `json:"parentProjectRefSelector,omitempty" tf:"-"`

	// Database region
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type DatabaseInitParameters struct {
}

type DatabaseObservation struct {

	// Host
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// Branch project ref
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Port
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// User
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Postgres version
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type DatabaseParameters struct {
}

// BranchSpec defines the desired state of Branch
type BranchSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BranchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BranchInitParameters `json:"initProvider,omitempty"`
}

// BranchStatus defines the observed state of Branch.
type BranchStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BranchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Branch is the Schema for the Branchs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-supabase}
type Branch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gitBranch) || (has(self.initProvider) && has(self.initProvider.gitBranch))",message="spec.forProvider.gitBranch is a required parameter"
	Spec   BranchSpec   `json:"spec"`
	Status BranchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BranchList contains a list of Branchs
type BranchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Branch `json:"items"`
}

// Repository type metadata.
var (
	Branch_Kind             = "Branch"
	Branch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Branch_Kind}.String()
	Branch_KindAPIVersion   = Branch_Kind + "." + CRDGroupVersion.String()
	Branch_GroupVersionKind = CRDGroupVersion.WithKind(Branch_Kind)
)

func init() {
	SchemeBuilder.Register(&Branch{}, &BranchList{})
}
