// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"

	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Apikey.
func (mg *Apikey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectRefRef,
		Selector:     mg.Spec.ForProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectRef")
	}
	mg.Spec.ForProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRefRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectRefRef,
		Selector:     mg.Spec.InitProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectRef")
	}
	mg.Spec.InitProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRefRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Branch.
func (mg *Branch) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentProjectRefRef,
		Selector:     mg.Spec.ForProvider.ParentProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentProjectRef")
	}
	mg.Spec.ForProvider.ParentProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentProjectRefRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentProjectRefRef,
		Selector:     mg.Spec.InitProvider.ParentProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentProjectRef")
	}
	mg.Spec.InitProvider.ParentProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentProjectRefRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Function.
func (mg *Function) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectRefRef,
		Selector:     mg.Spec.ForProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectRef")
	}
	mg.Spec.ForProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRefRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectRefRef,
		Selector:     mg.Spec.InitProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectRef")
	}
	mg.Spec.InitProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRefRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FunctionSecrets.
func (mg *FunctionSecrets) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectRefRef,
		Selector:     mg.Spec.ForProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectRef")
	}
	mg.Spec.ForProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRefRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectRefRef,
		Selector:     mg.Spec.InitProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectRef")
	}
	mg.Spec.InitProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRefRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Settings.
func (mg *Settings) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectRefRef,
		Selector:     mg.Spec.ForProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectRef")
	}
	mg.Spec.ForProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRefRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectRef),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectRefRef,
		Selector:     mg.Spec.InitProvider.ProjectRefSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectRef")
	}
	mg.Spec.InitProvider.ProjectRef = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectRefRef = rsp.ResolvedReference

	return nil
}
