// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SettingsInitParameters struct {

	// API settings as [serialised JSON](https://api.supabase.com/api/v1#/services/updatePostgRESTConfig)
	API *string `json:"api,omitempty" tf:"api,omitempty"`

	// Auth settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateV1AuthConfig)
	Auth *string `json:"auth,omitempty" tf:"auth,omitempty"`

	// Database settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateConfig)
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// Network settings as serialised JSON
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Pooler settings as serialised JSON
	Pooler *string `json:"pooler,omitempty" tf:"pooler,omitempty"`

	// Project reference ID
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/namespaced/project/v1alpha1.Project
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.NamespacedReference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.NamespacedSelector `json:"projectRefSelector,omitempty" tf:"-"`

	// Storage settings as serialised JSON
	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`
}

type SettingsObservation struct {

	// API settings as [serialised JSON](https://api.supabase.com/api/v1#/services/updatePostgRESTConfig)
	API *string `json:"api,omitempty" tf:"api,omitempty"`

	// Auth settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateV1AuthConfig)
	Auth *string `json:"auth,omitempty" tf:"auth,omitempty"`

	// Database settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateConfig)
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Network settings as serialised JSON
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Pooler settings as serialised JSON
	Pooler *string `json:"pooler,omitempty" tf:"pooler,omitempty"`

	// Project reference ID
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Storage settings as serialised JSON
	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`
}

type SettingsParameters struct {

	// API settings as [serialised JSON](https://api.supabase.com/api/v1#/services/updatePostgRESTConfig)
	// +kubebuilder:validation:Optional
	API *string `json:"api,omitempty" tf:"api,omitempty"`

	// Auth settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateV1AuthConfig)
	// +kubebuilder:validation:Optional
	Auth *string `json:"auth,omitempty" tf:"auth,omitempty"`

	// Database settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateConfig)
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// Network settings as serialised JSON
	// +kubebuilder:validation:Optional
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Pooler settings as serialised JSON
	// +kubebuilder:validation:Optional
	Pooler *string `json:"pooler,omitempty" tf:"pooler,omitempty"`

	// Project reference ID
	// +crossplane:generate:reference:type=github.com/wildbitca/provider-upjet-supabase/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectRef *string `json:"projectRef,omitempty" tf:"project_ref,omitempty"`

	// Reference to a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefRef *v1.NamespacedReference `json:"projectRefRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectRef.
	// +kubebuilder:validation:Optional
	ProjectRefSelector *v1.NamespacedSelector `json:"projectRefSelector,omitempty" tf:"-"`

	// Storage settings as serialised JSON
	// +kubebuilder:validation:Optional
	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`
}

// SettingsSpec defines the desired state of Settings
type SettingsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingsInitParameters `json:"initProvider,omitempty"`
}

// SettingsStatus defines the observed state of Settings.
type SettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Settings is the Schema for the Settingss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-supabase}
type Settings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SettingsSpec   `json:"spec"`
	Status            SettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsList contains a list of Settingss
type SettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Settings `json:"items"`
}

// Repository type metadata.
var (
	Settings_Kind             = "Settings"
	Settings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Settings_Kind}.String()
	Settings_KindAPIVersion   = Settings_Kind + "." + CRDGroupVersion.String()
	Settings_GroupVersionKind = CRDGroupVersion.WithKind(Settings_Kind)
)

func init() {
	SchemeBuilder.Register(&Settings{}, &SettingsList{})
}
