apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-supabase
  annotations:
    meta.crossplane.io/maintainer: "Wildbit"
    meta.crossplane.io/source: "https://github.com/wildbitca/provider-upjet-supabase"
    meta.crossplane.io/license: "Apache-2.0"
    meta.crossplane.io/iconURI: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48bGluZWFyR3JhZGllbnQgaWQ9ImEiIHgxPSIyMzcuMTA5IiB4Mj0iNDE5LjEwNiIgeTE9IjIyMy4yMTkiIHkyPSIxNDYuODkiIGdyYWRpZW50VHJhbnNmb3JtPSJtYXRyaXgoMSAwIDAgLTEgMCA1MTMpIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agb2Zmc2V0PSIwIiBzdHlsZT0ic3RvcC1jb2xvcjojMjQ5MzYxIi8+PHN0b3Agb2Zmc2V0PSIxIiBzdHlsZT0ic3RvcC1jb2xvcjojM2VjZjhlIi8+PC9saW5lYXJHcmFkaWVudD48cGF0aCBkPSJNMjk3LjYgNTAxYy0xMi45IDE2LjMtMzkuMiA3LjQtMzkuNS0xMy40TDI1My42IDE4M2gyMDQuOGMzNy4xIDAgNTcuOCA0Mi44IDM0LjcgNzEuOXoiIHN0eWxlPSJmaWxsOnVybCgjYSkiLz48bGluZWFyR3JhZGllbnQgaWQ9ImIiIHgxPSIyNDUuODI5IiB4Mj0iMzI4LjgyOSIgeTE9IjQxMS42ODEiIHkyPSIyNTUuNDM4IiBncmFkaWVudFRyYW5zZm9ybT0ibWF0cml4KDEgMCAwIC0xIDAgNTEzKSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIG9mZnNldD0iMCIgc3R5bGU9InN0b3AtY29sb3I6IzAwMCIvPjxzdG9wIG9mZnNldD0iMSIgc3R5bGU9InN0b3AtY29sb3I6IzAwMDtzdG9wLW9wYWNpdHk6MCIvPjwvbGluZWFyR3JhZGllbnQ+PHBhdGggZD0iTTI5Ny42IDUwMWMtMTIuOSAxNi4zLTM5LjIgNy40LTM5LjUtMTMuNEwyNTMuNiAxODNoMjA0LjhjMzcuMSAwIDU3LjggNDIuOCAzNC43IDcxLjl6IiBzdHlsZT0iZmlsbDp1cmwoI2IpO2ZpbGwtb3BhY2l0eTouMiIvPjxwYXRoIGQ9Ik0yMTQuNCAxMWMxMi45LTE2LjMgMzkuMi03LjQgMzkuNSAxMy40bDIgMzA0LjVINTMuN2MtMzcuMSAwLTU3LjgtNDIuOC0zNC43LTcxLjl6IiBzdHlsZT0iZmlsbDojM2VjZjhlIi8+PC9zdmc+"
    meta.crossplane.io/description: "Upjet-based Crossplane provider family for Supabase. Shared ProviderConfig for all Supabase sub-providers."
  labels:
    pkg.crossplane.io/provider-family: provider-family-supabase
spec:
  capabilities:
    - SafeStart
